"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default="django-insecure-0-6bf@)cs%)^u9+4coc+g&vjhf^90v0t6g^a!fgcfd4w^69l3$")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (User uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 104857600  # 100MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Custom User Model
AUTH_USER_MODEL = 'users.CustomUser'

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://localhost:5173',
    cast=lambda v: [s.strip() for s in v.split(',')]
)

CORS_ALLOW_CREDENTIALS = True

# Session cookie configuration. The default `Lax` SameSite policy is too
# strict for the Google Drive OAuth round-trip: the user starts on
# localhost:5173, we redirect them to Google, and Google redirects them
# back to localhost:8000/api/users/google_drive_callback/. The `sessionid`
# cookie must travel with that final top-level redirect, so we use `Lax`
# (Lax already allows top-level GETs — the issue is cross-origin sending).
# We additionally set the cookie domain to "localhost" so it is sent on
# BOTH ports (5173 and 8000). Without this, Django's default empty Domain
# means the cookie is host-only and may be scoped to the port that set it
# in some browser configurations.
# SESSION_COOKIE_SAMESITE = 'Lax'
# SESSION_COOKIE_DOMAIN = 'localhost'
# SESSION_COOKIE_SECURE = False  # dev only — must be True in production (HTTPS)
# SESSION_COOKIE_HTTPONLY = True
# CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_DOMAIN = 'localhost'
# CSRF_COOKIE_SECURE = False  # dev only

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
}

# Email Configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Frontend URL
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# Google OAuth Configuration
GOOGLE_OAUTH_CLIENT_ID = config('GOOGLE_OAUTH_CLIENT_ID', default='your-google-client-id.apps.googleusercontent.com')
GOOGLE_OAUTH_CLIENT_SECRET = config('GOOGLE_OAUTH_CLIENT_SECRET', default='')
GOOGLE_OAUTH_REDIRECT_URI = config(
    'GOOGLE_OAUTH_REDIRECT_URI',
    default='http://localhost:8000/api/users/google_drive_callback/',
)

# Fernet key for django-fernet-fields at-rest encryption. Empty default is
# fine for dev where GoogleOAuthToken rows may be empty; production must set
# this. The package reads from the `FERNET_KEYS` setting (a list of keys,
# oldest first, used for key rotation). We only support one key for now.
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default='')
if FIELD_ENCRYPTION_KEY:
    FERNET_KEYS = [FIELD_ENCRYPTION_KEY]

# n8n Webhook Configuration
N8N_WEBHOOK_URL = config('N8N_WEBHOOK_URL', default='http://localhost:5678/webhook/your-webhook-id')

# n8n Callback URL (where n8n sends results back to this backend)
N8N_CALLBACK_URL = config('N8N_CALLBACK_URL', default='http://localhost:8000/api/uploads/webhook_callback/')

# n8n webhooks for Jira/Trello CSV exports. Each platform has its own
# dedicated n8n workflow. The flow is: PM OS POSTs the sprint-plan sheet
# link, the parsed sheet_id, and (best-effort) a fresh Google access
# token to one of these URLs, n8n fetches the sheet, converts it to
# the right CSV shape, and POSTs the bytes back to N8N_CSV_CALLBACK_URL.
# The access_token is opportunistic — if the user has not connected
# Drive, the export still proceeds against the shared public sheet.
JIRA_N8N_WEBHOOK_URL = config('Jira_n8n_webhook_url', default='')
TRELLO_N8N_WEBHOOK_URL = config('Trello_n8n_webhook_url', default='')
N8N_CSV_CALLBACK_URL = config('N8N_CSV_CALLBACK_URL', default='http://localhost:8000/api/uploads/csv_callback/')


# ----------------------------------------------------------------------
# Celery + Redis configuration
#
# The SOW upload pipeline (Google token refresh + 300s n8n POST) is
# decoupled from the HTTP request thread via Celery. The `upload` view
# saves the FileUpload row, enqueues a task with `.delay()`, and returns
# 202 immediately. A separate worker process consumes the task and does
# the slow work. The frontend polls `GET /uploads/{id}/` for status.
#
# Both the broker (queue of pending tasks) and the result backend (where
# return values would be stored) use Redis by default. Override via
# backend/.env if you have a remote broker.
#
# Start the worker with: `celery -A config worker -l info`
# (in a separate terminal, with the venv activated and Redis running)
# ----------------------------------------------------------------------

# Broker is where tasks are queued. `localhost:6379/0` is the default
# Redis instance on the default DB. The `config('...')` call lets
# `CELERY_BROKER_URL` be overridden in backend/.env without code changes.
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')

# Result backend stores return values + task state. We don't actually
# use task return values (the FileUpload row is the source of truth) but
# Celery requires a backend to be configured. Using the same Redis
# instance keeps infrastructure to one service.
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')

# JSON only — no pickle. Pickle is a security risk if the broker is
# accessible to untrusted writers, and JSON is sufficient for the small
# payloads (just an int upload_id) we send.
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# Match Django's TIME_ZONE above (UTC).
CELERY_TIMEZONE = 'UTC'

# Task is acknowledged only after the task function returns successfully.
# If the worker is killed mid-task (Ctrl-C, OOM, host reboot), the message
# is requeued and retried on the next worker. Critical because the n8n
# POST can take up to 5 minutes — losing one because the worker restarted
# would silently leave the user's upload in 'processing' forever.
CELERY_TASK_ACKS_LATE = True

# If a worker process is lost mid-task, requeue the message instead of
# dropping it. Pairs with `ACKS_LATE` — without it, lost workers would
# ack-on-prefetch and the message would be gone.
CELERY_TASK_REJECT_ON_WORKER_LOST = True

# Hard kill at 10 minutes. n8n's webhook timeout is 300s; we give 2x
# headroom for retries before the worker kills the task forcefully.
CELERY_TASK_TIME_LIMIT = 600

# Soft kill at 9 minutes. The task gets `SoftTimeLimitExceeded` and can
# catch it to do cleanup (mark_failed, close file handles) before the
# hard kill at 10 min.
CELERY_TASK_SOFT_TIME_LIMIT = 540

# One task at a time per worker. Default is 4, which would mean a
# 4-upload batch is held in memory while the worker processes them
# serially (each takes minutes). With prefetch=1, a fresh worker can
# pick up the next message the moment the previous task finishes.
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
