"""
Google Drive OAuth utilities.

All Google OAuth token code lives here so view code stays clean. The single
public helper the upload view needs is `get_valid_access_token(user)` — it
loads the stored GoogleOAuthToken, refreshes the access token via the refresh
token if expired, and returns a fresh, currently-valid access token for use
against the Google Drive API.

Security notes:
- The `drive.file` scope is HARD-CODED on purpose. Do not move it to settings.
  A wider scope (e.g. `drive` for full Drive access) would let PM OS see the
  user's existing files and would fail Google's OAuth verification review.
- The refresh token never leaves the server. n8n only ever receives the
  short-lived access token, scoped to one upload.
- `prompt=consent` is mandatory in `build_auth_url`. Without it, Google skips
  the consent screen on re-auth and does NOT return a new refresh token, which
  means a user who disconnects and reconnects can only ever get one access
  token, never a refresh.
"""
from __future__ import annotations

from datetime import timedelta

import requests as http_requests
from django.conf import settings
from django.utils import timezone
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token

from users.models import GoogleOAuthToken


# Module-level constants. Scope is hard-coded — see module docstring.
GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_REVOKE_URL = "https://oauth2.googleapis.com/revoke"

# Least-privilege scope: read/write only files THIS app created, in any folder.
# https://developers.google.com/identity/protocols/oauth2/scopes#drive
DRIVE_FILE_SCOPE = "https://www.googleapis.com/auth/drive.file"


# Custom exceptions — caught by views and converted to clean HTTP responses.
class GoogleDriveError(Exception):
    """Generic Google Drive / OAuth failure."""


class GoogleDriveNotConnected(GoogleDriveError):
    """The user has not connected their Google Drive, or has disconnected.

    The frontend should react to this by prompting the user to (re)connect.
    """


def build_auth_url(state: str) -> str:
    """Construct the Google consent-screen URL.

    `state` is a one-time ticket generated by the calling view and stored in
    the user's session. We pass it through to `build_auth_url` (rather than
    hard-coding it here) so the caller controls its lifecycle.
    """
    if not settings.GOOGLE_OAUTH_CLIENT_ID:
        raise GoogleDriveError("GOOGLE_OAUTH_CLIENT_ID is not configured")

    params = {
        "client_id": settings.GOOGLE_OAUTH_CLIENT_ID,
        "redirect_uri": settings.GOOGLE_OAUTH_REDIRECT_URI,
        "response_type": "code",
        "scope": DRIVE_FILE_SCOPE,
        # `offline` is required to receive a refresh_token.
        "access_type": "offline",
        # `consent` forces the consent screen on re-auth so we always get a
        # fresh refresh_token. Without this, Google silently skips consent
        # and returns only an access_token, breaking long-term access.
        "prompt": "consent",
        # Carry prior grants forward so the user doesn't see scopes they
        # already approved for this client.
        "include_granted_scopes": "true",
        "state": state,
    }
    query = "&".join(f"{k}={http_requests.utils.quote(str(v))}" for k, v in params.items())
    return f"{GOOGLE_AUTH_URL}?{query}"


def exchange_code_for_tokens(code: str) -> dict:
    """Trade a one-time `code` for an access token + refresh token.

    Returns a dict with: access_token, refresh_token, expires_in, id_token,
    token_type. Raises GoogleDriveError on any non-2xx or missing field.
    """
    if not settings.GOOGLE_OAUTH_CLIENT_ID or not settings.GOOGLE_OAUTH_CLIENT_SECRET:
        raise GoogleDriveError(
            "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET must be configured"
        )

    payload = {
        "code": code,
        "client_id": settings.GOOGLE_OAUTH_CLIENT_ID,
        "client_secret": settings.GOOGLE_OAUTH_CLIENT_SECRET,
        "redirect_uri": settings.GOOGLE_OAUTH_REDIRECT_URI,
        "grant_type": "authorization_code",
    }

    try:
        response = http_requests.post(GOOGLE_TOKEN_URL, data=payload, timeout=30)
    except http_requests.RequestException as exc:
        raise GoogleDriveError(f"Network error talking to Google: {exc}") from exc

    if response.status_code != 200:
        # Try to surface Google's error description for easier debugging.
        try:
            err = response.json()
            description = err.get("error_description") or err.get("error") or response.text
        except ValueError:
            description = response.text
        # DEBUG: full error body so we can see why Google rejected the exchange.
        print(f"\n[GD TOKEN EXCHANGE FAILED] status={response.status_code} body={response.text[:400]}")
        raise GoogleDriveError(f"Token exchange failed: {description}")

    body = response.json()
    # DEBUG: show what Google actually sent back. Remove once Drive is working.
    print(f"\n[GD TOKEN RESPONSE] keys={list(body.keys())} "
          f"has_access={bool(body.get('access_token'))} "
          f"has_refresh={bool(body.get('refresh_token'))} "
          f"expires_in={body.get('expires_in')}")
    required = ("access_token", "expires_in")
    for field in required:
        if field not in body:
            raise GoogleDriveError(f"Token response missing required field: {field}")

    return body


def refresh_access_token(refresh_token: str) -> dict:
    """Exchange a refresh_token for a new access_token.

    Returns a dict with: access_token, expires_in, token_type, scope. Note
    that Google does NOT return a new refresh_token here — reuse the stored
    one. (Google occasionally rotates the refresh_token; if that happens the
    response will include one, and we should update our stored copy.)
    """
    if not settings.GOOGLE_OAUTH_CLIENT_ID or not settings.GOOGLE_OAUTH_CLIENT_SECRET:
        raise GoogleDriveError(
            "GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET must be configured"
        )

    payload = {
        "refresh_token": refresh_token,
        "client_id": settings.GOOGLE_OAUTH_CLIENT_ID,
        "client_secret": settings.GOOGLE_OAUTH_CLIENT_SECRET,
        "grant_type": "refresh_token",
    }

    try:
        response = http_requests.post(GOOGLE_TOKEN_URL, data=payload, timeout=30)
    except http_requests.RequestException as exc:
        raise GoogleDriveError(f"Network error talking to Google: {exc}") from exc

    if response.status_code != 200:
        try:
            err = response.json()
            error_code = err.get("error", "")
            description = err.get("error_description") or response.text
        except ValueError:
            error_code = ""
            description = response.text
        # `invalid_grant` means the refresh token has been revoked or expired.
        # The caller should treat this as "user needs to re-consent".
        if error_code == "invalid_grant":
            raise GoogleDriveNotConnected(
                "Your Google Drive connection has expired. Please reconnect."
            ) from None
        raise GoogleDriveError(f"Token refresh failed: {description}")

    return response.json()


def get_valid_access_token(user) -> str:
    """Return a currently-valid access token for the user, refreshing if needed.

    Raises GoogleDriveNotConnected if the user has no GoogleOAuthToken row
    OR if the row has no refresh_token (i.e. they only ever logged in via the
    ID-token flow and never completed the Connect Drive flow). The frontend
    should react to this by showing the Connect Drive button.
    """
    try:
        token_row = user.google_oauth
    except GoogleOAuthToken.DoesNotExist:
        raise GoogleDriveNotConnected(
            "Please connect your Google Drive to save outputs to your Drive."
        )

    if not token_row.has_refresh_token():
        raise GoogleDriveNotConnected(
            "Please connect your Google Drive to save outputs to your Drive."
        )

    # If still valid, return as-is. We refresh a minute early to avoid a
    # token that expires mid-upload.
    if not token_row.is_token_expired():
        return token_row.access_token

    refreshed = refresh_access_token(token_row.refresh_token)
    new_access = refreshed.get("access_token")
    if not new_access:
        raise GoogleDriveError("Token refresh succeeded but no access_token returned")

    # If Google rotated the refresh_token, persist the new one. (Rare, but it
    # happens — e.g. after the user re-consents via prompt=consent.)
    new_refresh = refreshed.get("refresh_token", token_row.refresh_token)
    expires_in = int(refreshed.get("expires_in", 3600))

    token_row.access_token = new_access
    token_row.refresh_token = new_refresh
    token_row.expires_at = timezone.now() + timedelta(seconds=expires_in)
    token_row.save(update_fields=["access_token", "refresh_token", "expires_at", "updated_at"])

    return new_access


def disconnect(user) -> None:
    """Best-effort revoke the user's stored tokens, then delete the row.

    Network errors talking to Google's revoke endpoint are swallowed: the
    user's row is deleted regardless, so they immediately stop working from
    PM OS's side even if Google's revoke endpoint is down.
    """
    try:
        token_row = user.google_oauth
    except GoogleOAuthToken.DoesNotExist:
        return

    access = token_row.access_token
    if access:
        try:
            http_requests.post(
                GOOGLE_REVOKE_URL,
                params={"token": access},
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                timeout=10,
            )
        except http_requests.RequestException:
            # Best-effort. Delete the row regardless.
            print("Warning: failed to revoke Google access token (network error)")

    GoogleOAuthToken.objects.filter(user=user).delete()


def decode_id_token(id_token_str: str) -> dict:
    """Verify and decode a Google ID token from a token-endpoint response.

    Returns the verified claims dict (sub, email, etc.). Raises ValueError
    on verification failure.
    """
    return id_token.verify_oauth2_token(
        id_token_str,
        google_requests.Request(),
        settings.GOOGLE_OAUTH_CLIENT_ID,
    )
