# Generated by Django 6.0.6 on 2026-07-09 13:20

import users.encryption
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='access_token',
            field=users.encryption.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='googleoauthtoken',
            name='refresh_token',
            field=users.encryption.EncryptedTextField(blank=True, null=True),
        ),
    ]
